# when running hexo in a subdirectory (e.g. domain.tld/blog), remove leading slashes ( "/archives" -> "archives" )

# Place your favicon.ico to /source directory.
favicon: /favicon.ico
avatar: /avatar.jpg

# Set default keywords (Use a comma to separate)
keywords: 当然我没扯淡,DE清平 


# 请前往https://highlightjs.org下载。把下载好的css放入主题下css文件夹
# 注意请关闭hexo自带高亮
highlight_theme: github-gist

#account 

github: https://github.com/duzhihao-github
weibo: https://weibo.com/u/1783756832/home?wvr=5#_loginLayer_1521011243864

# Static files
css: css
js: js
img: images